# Generated by Django 5.2 on 2025-05-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Zadvorkislozhnogo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
