# Generated by Django 5.2.1 on 2025-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zadvorkislozhnogo', '0002_alter_audiobook_audio_file_alter_audiobook_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AddField(
            model_name='poem',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
