# Generated by Django 5.2.1 on 2025-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zadvorkislozhnogo', '0003_audiobook_views_count_poem_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
