# Generated by Django 5.2 on 2025-06-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zadvorkislozhnogo", "0007_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterUniqueTogether(
            name="genre",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="audiobook",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Zadvorkislozhnogo.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AddField(
            model_name="poem",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Zadvorkislozhnogo.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Zadvorkislozhnogo.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.RemoveField(
            model_name="genre",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="object_id",
        ),
    ]
