# Generated by Django 5.2.1 on 2025-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zadvorkislozhnogo', '0008_alter_genre_options_alter_genre_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
    ]
