# Generated by Django 5.2.1 on 2025-06-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zadvorkislozhnogo', '0010_about_document_faq_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
